- name: "Playing with Ansible"
  hosts: rocky
  tasks:
    - name: "Read the passwd file"
      ansible.builtin.command: cat /etc/passwd
      register: passwd_contents
    - name: "Save passwd content to passwd_contents"
      ansible.builtin.debug:
        var: "passwd_contents"
    - name: "Print command status to the CLI"
      ansible.builtin.debug:
        msg: "command status {{ passwd_contents['rc'] }}"
