- name: "Playing with Ansible"
  hosts: rocky
  connection: ssh
  become: true
  # gather_facts: false
  tasks:
    - name: Update rocky packages
      ansible.builtin.dnf:
        update_cache: true
        name: "*"
        state: latest
