- name: "Playing with Ansible"
  hosts: ubuntu
  connection: ssh
  become: true
  # gather_facts: false
  tasks:
    - name: Install pip
      ansible.builtin.apt:
        update_cache: true
        name: "pip"
        state: latest
