- name: "Playing with Ansible"
  hosts: 192.168.99.151
  connection: ssh
  become: true
  # gather_facts: false
  tasks:

  - name: Install pip
    ansible.builtin.apt:
      update_cache: yes
      name: "pip"
      state: latest