- name: "Playing with Ansible"
  hosts: ubuntu
  connection: ssh
  become: true
  # gather_facts: false
  tasks:

  - name: Update ubuntu packages
    ansible.builtin.apt:
      update_cache: yes
      name: "*"
      state: latest