- name: "Playing with Ansible"
  hosts: all
  connection: ssh
  become: true
  # gather_facts: false
  tasks:
    - name: Show all facts
      debug:
        # var: ansible_facts # all facts
        # var: ansible_facts.default_ipv4.macaddress # old format
        var: ansible_facts["default_ipv4"]["macaddress"] # new format
